import { renderStoryGenerationSpinner } from './storyAsyncButtonPresentation.js';
function escapeHtml(_0x3a53ab) {
  return String(_0x3a53ab ?? '')["replace"](/&/g, '&amp;')["replace"](/</g, "&lt;")['replace'](/>/g, "&gt;")["replace"](/"/g, '&quot;')["replace"](/'/g, '&#39;');
}
function renderStepNavigation(_0x32e239 = {}) {
  return "<nav class=\"story-step-navigation\" data-step-count=\"" + (_0x32e239["items"]?.["length"] || 0x3) + "\" data-active-step=\"" + escapeHtml(_0x32e239["activeStep"]) + "\" aria-label=\"剧本制作步骤\">\n    " + (_0x32e239["items"] || [])['map'](_0x4034a7 => "<button type=\"button\" class=\"story-step " + (_0x4034a7["active"] ? "is-active" : '') + "\" data-story-step=\"" + _0x4034a7['id'] + "\" aria-current=\"" + (_0x4034a7["active"] ? "step" : 'false') + "\" aria-keyshortcuts=\"" + (_0x4034a7["number"] ?? _0x4034a7['id']) + '\x22\x20' + (_0x4034a7['disabled'] ? "disabled" : '') + ">\n        <span>" + (_0x4034a7["number"] ?? _0x4034a7['id']) + "</span>" + escapeHtml(_0x4034a7["label"]) + "\n      </button>")['join']('') + "\n  </nav>";
}
function renderEpisodeSwitcher(_0x3c2f02 = {}) {
  const _0x3925b9 = _0x3c2f02['options'] || [];
  const _0x2bceb3 = _0x3925b9["length"] > 0x0;
  return "<div class=\"story-episode-switcher " + (_0x2bceb3 ? "has-options" : '') + "\">\n    <button type=\"button\" class=\"story-episode-toolbar-current story-menu-trigger\" data-story-episode-state=\"" + (_0x3c2f02["isCurrentPage"] ? "active" : "inactive") + '\x22\x20' + (_0x3c2f02["isCurrentPage"] ? "aria-current=\"page\"" : "data-story-open-episode=\"" + escapeHtml(_0x3c2f02['currentEpisodeId']) + '\x22') + '\x20' + (_0x2bceb3 ? "aria-haspopup=\"menu\"" : '') + ">\n      <span class=\"story-episode-toolbar-current-label\">" + escapeHtml(_0x3c2f02["currentEpisodeName"]) + "</span>\n      " + (_0x2bceb3 ? "<span class=\"story-episode-switcher-chevron\" aria-hidden=\"true\"></span>" : '') + "\n    </button>\n    " + (_0x2bceb3 ? '<div\x20class=\x22story-episode-switcher-menu\x22\x20role=\x22menu\x22\x20aria-label=\x22切换已生成分集\x22>\x0a\x20\x20\x20\x20\x20\x20' + _0x3925b9["map"](_0x1c0365 => "<button type=\"button\" class=\"story-episode-switcher-option\" data-story-open-episode=\"" + escapeHtml(_0x1c0365['id']) + "\" role=\"menuitem\">\n          <span>" + escapeHtml(_0x1c0365["name"]) + "</span>\n          <small>已生成 " + _0x1c0365["clipCount"] + " 个分镜片段</small>\n        </button>")["join"]('') + "\n    </div>" : '') + '\x0a\x20\x20</div>';
}
function renderEpisodeToolbarSide(_0x4e9b34 = {}) {
  const _0x53998a = _0x4e9b34["canvasSyncPending"] === !![];
  const _0x466157 = _0x53998a ? "disabled aria-disabled=\"true\"" : '';
  return "<div class=\"story-episode-toolbar-side\">\n      " + renderEpisodeSwitcher(_0x4e9b34['episodeSwitcher']) + "\n      <div class=\"story-episode-toolbar-actions\">\n        <div class=\"story-canvas-sync-menu-wrap\">\n          <button type=\"button\" class=\"story-workbench-action-button story-canvas-sync-trigger story-menu-trigger" + (_0x53998a ? '\x20is-pending' : '') + "\" data-story-action=\"toggle-canvas-sync-menu\" " + _0x466157 + " aria-busy=\"" + (_0x53998a ? "true" : "false") + '\x22\x20aria-haspopup=\x22menu\x22\x20aria-expanded=\x22false\x22>\x0a\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20' + (_0x53998a ? "<span class=\"story-canvas-sync-spinner\" aria-hidden=\"true\"></span>" : '') + '\x0a\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20<span>' + (_0x53998a ? "加入中…" : '加入画布') + '</span><span\x20class=\x22story-canvas-sync-chevron\x22\x20aria-hidden=\x22true\x22></span>\x0a\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20</button>\x0a\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20<div\x20class=\x22story-canvas-sync-menu\x22\x20role=\x22menu\x22\x20aria-hidden=\x22true\x22>\x0a\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20<button\x20type=\x22button\x22\x20class=\x22story-canvas-sync-option\x22\x20data-story-action=\x22sync-episode-to-canvas\x22\x20role=\x22menuitem\x22\x20' + _0x466157 + ">\n              <strong>同步本集到画布</strong><small>只更新当前分集的分镜视频</small>\n            </button>\n            <button type=\"button\" class=\"story-canvas-sync-option\" data-story-action=\"sync-project-to-canvas\" role=\"menuitem\" " + _0x466157 + ">\n              <strong>同步整个项目到画布</strong><small>加入项目设定、素材与当前集视频</small>\n            </button>\n          </div>\n        </div>\n        <div class=\"story-canvas-sync-menu-wrap story-clip-export-menu-wrap\">\n          <button type=\"button\" class=\"story-workbench-action-button story-canvas-sync-trigger story-menu-trigger\" data-story-action=\"toggle-canvas-sync-menu\" aria-haspopup=\"menu\" aria-expanded=\"false\">\n            <span>导出</span><span class=\"story-canvas-sync-chevron\" aria-hidden=\"true\"></span>\n          </button>\n          <div class=\"story-canvas-sync-menu story-clip-export-menu\" role=\"menu\" aria-label=\"导出视频片段\" aria-hidden=\"true\">\n            <button type=\"button\" class=\"story-canvas-sync-option\" data-story-action=\"export-current-clip\" role=\"menuitem\">\n              <strong>导出当前片段</strong><small>导出当前选中的视频版本</small>\n            </button>\n            <button type=\"button\" class=\"story-canvas-sync-option\" data-story-action=\"export-episode-clips\" role=\"menuitem\">\n              <strong>导出本集全部片段</strong><small>自动跳过还没有视频的片段</small>\n            </button>\n          </div>\n        </div>\n      </div>\n    </div>";
}
export function createStoryWorkspaceChromePresentation() {
  function _0x14cf31(_0x4798c0 = {}) {
    if (_0x4798c0['kind'] === "episode") {
      return "<div class=\"story-project-toolbar story-project-toolbar--episode\">\n      <button type=\"button\" class=\"story-toolbar-back\" data-story-action=\"back-home\"><span class=\"story-toolbar-back-icon\" aria-hidden=\"true\"></span><span>" + escapeHtml(_0x4798c0['projectLabel'] || '剧本项目') + '</span></button>\x0a\x20\x20\x20\x20\x20\x20' + renderStepNavigation(_0x4798c0["steps"]) + "\n      " + renderEpisodeToolbarSide(_0x4798c0) + "\n    </div>";
    }
    return '<div\x20class=\x22story-project-toolbar\x22>\x0a\x20\x20\x20\x20<button\x20type=\x22button\x22\x20class=\x22story-toolbar-back\x22\x20data-story-action=\x22back-home\x22><span\x20class=\x22story-toolbar-back-icon\x22\x20aria-hidden=\x22true\x22></span><span>' + escapeHtml(_0x4798c0["projectLabel"] || "剧本项目") + "</span></button>\n    " + renderStepNavigation(_0x4798c0["steps"]) + "\n    <div class=\"story-episode-toolbar-side\">" + (_0x4798c0["episodeSwitcher"] ? renderEpisodeSwitcher(_0x4798c0["episodeSwitcher"]) : '') + (_0x4798c0["collaborationAvailable"] ? "<button type=\"button\" class=\"story-secondary-button\" data-collaboration-toggle>AI 协作</button>" : '') + "</div>\n  </div>";
  }
  function _0x45b4c8(_0x21e3ff = {}) {
    const _0x38b45b = "\n      " + (_0x21e3ff["showPrevious"] ? "<button type=\"button\" class=\"story-secondary-button button-press-feedback\" data-story-action=\"previous-step\"><span>上一步</span></button>" : '') + "\n      <button type=\"button\" class=\"story-next-button\" data-story-action=\"" + escapeHtml(_0x21e3ff["nextAction"]) + '\x22\x20' + (_0x21e3ff["busy"] ? 'disabled' : '') + '\x20aria-busy=\x22' + Boolean(_0x21e3ff["busy"]) + '\x22>' + (_0x21e3ff["busy"] ? renderStoryGenerationSpinner({
      'button': !![]
    }) : '') + "<span>" + escapeHtml(_0x21e3ff["nextLabel"]) + "</span>" + (_0x21e3ff['busy'] ? '' : "<span class=\"story-next-arrow\" aria-hidden=\"true\">→</span>") + "</button>";
    return "<footer class=\"story-page-footer\">\n    <div>\n      <strong>" + escapeHtml(_0x21e3ff["title"]) + "</strong>\n      <small>" + escapeHtml(_0x21e3ff["hint"]) + "</small>\n    </div>\n    <div class=\"story-page-footer-actions\">\n      " + (_0x21e3ff["actionsMarkup"] || _0x38b45b) + "\n    </div>\n  </footer>";
  }
  return Object["freeze"]({
    'renderFooter': _0x45b4c8,
    'renderToolbar': _0x14cf31
  });
}