import * as a995_0x3c27b2 from './project.js';
import { saveDesktopProject } from '../services/desktopProjectService.js';
import { t } from '../i18n/index.js';
import { captureCanvasProjectSaveTransaction, commitCanvasProjectSave, releaseCanvasProjectSave } from './canvasProjectSaveTransaction.js';
import { createWorkspacePersistencePresentation } from './workspacePersistencePresentation.js';
import { assertCanvasProjectSaveAllowed } from '../services/canvasProjectAccess.js';
const projectDropdownText = (_0x1dd790, _0x26ca7 = {}) => t('projectDropdown.' + _0x1dd790, _0x26ca7);
export function createCanvasProjectSaveController({
  windowObject = globalThis["window"],
  getRoot: _0x543123,
  getProjectPackageExportSource: _0x2332af,
  getActiveCanvasProjectContext: _0x58664f,
  getCurrentProjectName: _0x3be007,
  buildProjectContextFromLoadResult: _0x59c7d8,
  reconcileProjectSessionAfterSave: _0x1bab2b,
  playProjectSaveAbsorb: _0x2536f1,
  fetchProjects: _0x3ab34d,
  openSaveDialog: _0x49236a,
  getShortcutSaveProjectName: _0x5b5c0e,
  isAutoGeneratedProjectName: _0x3745d9,
  projectNameExistsInProjectList: _0x1645b2,
  showToast: _0x45c4e0
} = {}) {
  const _0x44d340 = windowObject;
  const _0x2ac2d7 = createWorkspacePersistencePresentation({
    'getRoot': _0x543123
  });
  let _0x105e5f = 0x0;
  const _0x54af93 = () => {
    _0x105e5f += 0x1;
    _0x2ac2d7["update"]({
      'status': "saving"
    });
    return () => {
      _0x105e5f -= 0x1;
      if (!_0x105e5f) {
        _0x2ac2d7['update']({
          'status': 'saved'
        });
      }
    };
  };
  async function _0x1a155f(_0x48cd79 = {}) {
    let _0x401018;
    try {
      const _0x345a1d = _0x2332af(_0x48cd79);
      _0x401018 = captureCanvasProjectSaveTransaction({
        'manager': _0x44d340["CanvasTabManager"],
        'exportSource': _0x345a1d,
        'projectContext': _0x58664f()
      });
      _0x44d340["showGlobalLoading"]?.(projectDropdownText("savingLocal"));
      const {
        projectContext: _0x3eb4bf
      } = _0x401018;
      const _0x400e5d = await saveDesktopProject(_0x345a1d["projectName"] || _0x3be007(), _0x345a1d['multiData'], {
        'mode': "saveAs",
        'projectId': _0x3eb4bf["projectId"],
        'recentId': _0x3eb4bf["recentId"]
      });
      if (!_0x400e5d || _0x400e5d["canceled"]) {
        return;
      }
      commitCanvasProjectSave(_0x401018, _0x59c7d8(_0x400e5d, {
        ..._0x3eb4bf,
        'projectName': _0x345a1d["projectName"]
      }));
      _0x45c4e0(projectDropdownText("saveAsSucceeded", {
        'filename': _0x400e5d["filename"]
      }));
      _0x3ab34d();
    } catch (_0x5aa69b) {
      if (_0x5aa69b?.["code"] !== "PROJECT_SAVE_FORBIDDEN") {
        console['error']("[desktopProject] saveAs failed:", _0x5aa69b);
      }
      _0x45c4e0(_0x5aa69b?.["message"] || projectDropdownText("saveAsFailed"), _0x5aa69b?.["code"] === "PROJECT_SAVE_FORBIDDEN" ? "warn" : 'error');
    } finally {
      releaseCanvasProjectSave(_0x401018);
      if (_0x44d340["hideGlobalLoading"]) {
        _0x44d340["hideGlobalLoading"]();
      }
    }
  }
  function _0x464c42(_0x4e9e02, _0x102b5f = {}) {
    return captureCanvasProjectSaveTransaction({
      'manager': _0x44d340["CanvasTabManager"],
      'exportSource': _0x2332af({
        ..._0x102b5f,
        'projectName': _0x4e9e02
      }),
      'projectContext': _0x58664f(),
      'rename': _0x102b5f['renameActiveCanvas'] === !![]
    });
  }
  async function _0x70b94a(_0x460792, _0x4332f8 = {}, _0x56f561 = null) {
    let _0x37885a = () => {};
    try {
      _0x56f561 ||= _0x464c42(_0x460792, _0x4332f8);
      _0x37885a = _0x54af93();
      const {
        exportSource: _0x14a8b3,
        canvasId: _0xaa2dd2,
        projectContext: _0x3ca28d
      } = _0x56f561;
      const _0x66b50d = _0x3ca28d["projectId"];
      const _0x5aeeef = _0x4332f8['saveAs'] === !![] || _0x3ca28d["isTemporary"] ? _0x460792 : _0x3ca28d['projectId'] || _0x460792;
      const _0x5a7241 = await a995_0x3c27b2["saveProject"](_0x5aeeef, _0x14a8b3["multiData"]);
      if (_0x5a7241?.['canceled']) {
        return ![];
      }
      if (!_0x5a7241?.["success"]) {
        throw new Error(projectDropdownText("saveFailed"));
      }
      if (_0x5a7241["success"]) {
        const _0xa5e1ae = commitCanvasProjectSave(_0x56f561, _0x59c7d8(_0x5a7241, {
          ..._0x3ca28d,
          'projectId': _0x5aeeef,
          'projectName': _0x460792,
          'filename': _0x5a7241["filename"],
          'recentId': '',
          'displayPath': '',
          'lastModified': 0x0
        }), {
          'rename': _0x4332f8['renameActiveCanvas'] === !![]
        });
        _0x44d340["CanvasTabManager"]?.["_activeId"] === _0xaa2dd2 && (await _0x1bab2b(_0x66b50d));
        _0x2536f1();
        _0x45c4e0(projectDropdownText("saveSucceeded", {
          'name': _0x460792
        }));
        await _0x3ab34d();
        return _0xa5e1ae;
      }
    } catch (_0x7b1cce) {
      if (_0x7b1cce?.["code"] !== 'PROJECT_SAVE_FORBIDDEN') {
        console["error"]("[saveProject] JSON 保存失败:", _0x7b1cce);
      }
      _0x45c4e0(_0x7b1cce?.["code"] === "PROJECT_SAVE_FORBIDDEN" ? _0x7b1cce["message"] : projectDropdownText('saveFailed'), _0x7b1cce?.["code"] === "PROJECT_SAVE_FORBIDDEN" ? "warn" : "error");
      return ![];
    } finally {
      releaseCanvasProjectSave(_0x56f561);
      _0x37885a();
    }
  }
  async function _0x33c29b({
    waitForDialog = ![]
  } = {}) {
    try {
      assertCanvasProjectSaveAllowed(_0x2332af()["multiData"], _0x44d340["CanvasTabManager"]);
    } catch (_0x5dd47d) {
      _0x45c4e0(_0x5dd47d["message"], "warn");
      return ![];
    }
    const _0x2128e1 = _0x5b5c0e();
    if (!_0x2128e1 || _0x3745d9(_0x2128e1)) {
      const _0x20ab9b = _0x49236a({
        'defaultName': _0x2128e1
      });
      return waitForDialog ? (await _0x20ab9b) === !![] : ![];
    }
    const _0x4a3f3d = _0x464c42(_0x2128e1);
    const _0x473276 = _0x54af93();
    try {
      let _0x3420ff = ![];
      try {
        _0x3420ff = await _0x1645b2(_0x2128e1);
      } catch (_0x291813) {
        console["error"]("[saveCurrentProjectFromShortcut] 项目列表校验失败:", _0x291813);
        _0x45c4e0(projectDropdownText('listLoadFailed'), 'error');
        return ![];
      }
      if (!_0x3420ff) {
        if (_0x44d340["CanvasTabManager"]?.['_activeId'] !== _0x4a3f3d["canvasId"]) {
          return ![];
        }
        const _0x20aad4 = _0x49236a({
          'defaultName': _0x2128e1
        });
        return waitForDialog ? (await _0x20aad4) === !![] : ![];
      }
      return await _0x70b94a(_0x2128e1, {}, _0x4a3f3d);
    } finally {
      releaseCanvasProjectSave(_0x4a3f3d);
      _0x473276();
    }
  }
  return {
    'saveProject': _0x70b94a,
    'saveProjectAsLocal': _0x1a155f,
    'saveCurrentProjectFromShortcut': _0x33c29b
  };
}