import a975_0x319b52, { CanvasCommandError, CanvasCommandRegistry, createCanvasCommandError, createCanvasCommandRegistry } from './commandRegistry.js';
import { executeCanvasCommand, executeCanvasCommandSync, executeCanvasCommandPlan, hasCanvasCommandPlanVariableReference } from './commandExecutor.js';
import { createCanvasCommandContext } from './commandContext.js';
import { registerGenerationCommands } from './generationCommands.js';
import { registerEditingCommands } from './editingCommands.js';
import { registerGraphCommands } from './graphCommands.js';
import { registerLayoutCommands } from './layoutCommands.js';
import { registerMediaToolCommands } from './mediaToolCommands.js';
import { registerModelParamCommands } from './modelParamCommands.js';
import { registerNodeExportCommands } from './nodeExportCommands.js';
import { registerPanoramaSceneCommands } from './panoramaSceneCommands.js';
import { registerPromptCommands } from './promptCommands.js';
import { registerSelectionCommands } from './selectionCommands.js';
import { registerStoryboardCommands } from './storyboardCommands.js';
import { registerTaskCommands } from './taskCommands.js';
import { registerViewportCommands } from './viewportCommands.js';
export function registerDefaultCanvasCommands(_0x216b78 = a975_0x319b52) {
  registerGraphCommands(_0x216b78);
  registerEditingCommands(_0x216b78);
  registerSelectionCommands(_0x216b78);
  registerViewportCommands(_0x216b78);
  registerPromptCommands(_0x216b78);
  registerModelParamCommands(_0x216b78);
  registerLayoutCommands(_0x216b78);
  registerMediaToolCommands(_0x216b78);
  registerStoryboardCommands(_0x216b78);
  registerTaskCommands(_0x216b78);
  registerGenerationCommands(_0x216b78);
  registerNodeExportCommands(_0x216b78);
  registerPanoramaSceneCommands(_0x216b78);
  return _0x216b78;
}
registerDefaultCanvasCommands(a975_0x319b52);
export { CanvasCommandError, CanvasCommandRegistry, createCanvasCommandContext, createCanvasCommandError, createCanvasCommandRegistry, a975_0x319b52 as canvasCommandRegistry, executeCanvasCommand, executeCanvasCommandSync, executeCanvasCommandPlan, hasCanvasCommandPlanVariableReference };