export const AGENT_SKILL_PANEL_TEXT = Object["freeze"]({
  'zh-CN': Object["freeze"]({
    'skillPanelTitle': "Skills",
    'skillPanelDesc': "通过 Agent 对话创建技能；这里用于导入、启用、编辑和删除。",
    'skillManage': "管理 Skills",
    'skillPickerDefault': 'Skill',
    'skillPickerAuto': "自动匹配",
    'skillPickerEmpty': '暂无可用\x20Skill。',
    'skillEmpty': '尚未发现本地\x20Skill。可以让\x20Agent\x20创建，或导入包含\x20SKILL.md\x20的\x20Skill\x20文件夹。',
    'skillInsert': '使用',
    'skillEnable': '启用',
    'skillDisable': '停用',
    'skillRefresh': '刷新\x20Skills',
    'skillRefreshDone': "已加载 {count} 个本地 Skill。",
    'skillRefreshFailed': "刷新 Skill 失败，请检查技能目录。",
    'skillDiagnostics': "有 {count} 个 Skill 未能加载。",
    'skillClose': "关闭 Skills",
    'skillImport': "导入 Skill",
    'skillImportDone': '已导入\x20Skill：{name}',
    'skillImportFailed': 'Skill\x20导入失败。',
    'skillImportDuplicate': '同名\x20Skill\x20已经安装。',
    'skillImportInvalid': "所选文件夹不是有效的 Skill，请检查 SKILL.md。",
    'skillImportRestricted': "已导入 Skill：{name}；scripts 或超限参考文件未复制。",
    'skillImportRefreshFailed': "Skill 已导入，但列表刷新失败；请点击刷新。",
    'skillCreate': '让\x20Agent\x20创建',
    'skillCreatePrompt': "帮我创建一个 Skill，用来",
    'skillEdit': '编辑',
    'skillDelete': '删除',
    'skillDeleteConfirmLabel': '确认删除\x20Skill：{name}',
    'skillDeleteConfirm': '确定',
    'skillDeleteCancel': '取消',
    'skillDeleteDone': "已删除 Skill：{name}",
    'skillDeleteFailed': "Skill 删除失败。",
    'skillDeleteRefreshFailed': 'Skill\x20已删除，但列表刷新失败；请点击刷新。',
    'skillEditorCreateTitle': "新建 Skill",
    'skillEditorEditTitle': "编辑 Skill",
    'skillNameLabel': "名称（保存后不可修改）",
    'skillNamePlaceholder': "例如 product-copy",
    'skillTitleLabel': '显示名称',
    'skillDescriptionLabel': "何时使用",
    'skillTriggersLabel': '触发词',
    'skillTriggersPlaceholder': "用逗号分隔，例如 产品文案, 改写卖点",
    'skillInstructionsLabel': "执行说明",
    'skillSave': '保存',
    'skillEditorCancel': '取消',
    'skillValidationRequired': "“何时使用”和“执行说明”不能为空。",
    'skillValidationName': "名称只能包含小写字母、数字和连字符，最长 64 个字符。",
    'skillSaveDone': "已保存 Skill：{name}",
    'skillSaveFailed': "Skill 保存失败。",
    'skillSaveDuplicate': "同名 Skill 已经存在。",
    'skillSaveReadOnly': "这个 Skill 来自外部，只能在文件夹中编辑。",
    'skillSaveRefreshFailed': "Skill 已保存，但列表刷新失败；请点击刷新。"
  }),
  'en-US': Object["freeze"]({
    'skillPanelTitle': "Skills",
    'skillPanelDesc': "Create Skills through Agent conversation; import, enable, edit, or delete them here.",
    'skillManage': "Manage Skills",
    'skillPickerDefault': "Skill",
    'skillPickerAuto': "Automatic",
    'skillPickerEmpty': "No available Skills.",
    'skillEmpty': 'No\x20local\x20Skills\x20found.\x20Ask\x20the\x20Agent\x20to\x20create\x20one,\x20or\x20import\x20a\x20folder\x20containing\x20SKILL.md.',
    'skillInsert': 'Use',
    'skillEnable': "Enable",
    'skillDisable': "Disable",
    'skillRefresh': "Refresh Skills",
    'skillRefreshDone': 'Loaded\x20{count}\x20local\x20Skill(s).',
    'skillRefreshFailed': "Could not refresh Skills. Check the Skill folder.",
    'skillDiagnostics': "{count} Skill package(s) could not be loaded.",
    'skillClose': 'Close\x20Skills',
    'skillImport': 'Import\x20Skill',
    'skillImportDone': "Imported Skill: {name}",
    'skillImportFailed': "Skill import failed.",
    'skillImportDuplicate': "A Skill with this name is already installed.",
    'skillImportInvalid': "The selected folder is not a valid Skill. Check SKILL.md.",
    'skillImportRestricted': 'Imported\x20Skill:\x20{name}.\x20Scripts\x20or\x20oversized\x20references\x20were\x20not\x20copied.',
    'skillImportRefreshFailed': "The Skill was imported, but the list could not refresh. Refresh it again.",
    'skillCreate': "Ask Agent to create",
    'skillCreatePrompt': "Create a Skill that helps me ",
    'skillEdit': "Edit",
    'skillDelete': "Delete",
    'skillDeleteConfirmLabel': "Confirm deleting Skill: {name}",
    'skillDeleteConfirm': "Confirm",
    'skillDeleteCancel': 'Cancel',
    'skillDeleteDone': 'Deleted\x20Skill:\x20{name}',
    'skillDeleteFailed': "Skill deletion failed.",
    'skillDeleteRefreshFailed': "The Skill was deleted, but the list could not refresh. Refresh it again.",
    'skillEditorCreateTitle': "New Skill",
    'skillEditorEditTitle': "Edit Skill",
    'skillNameLabel': 'Name\x20(cannot\x20be\x20changed\x20after\x20saving)',
    'skillNamePlaceholder': 'For\x20example,\x20product-copy',
    'skillTitleLabel': "Display name",
    'skillDescriptionLabel': "When to use",
    'skillTriggersLabel': "Triggers",
    'skillTriggersPlaceholder': 'Comma-separated,\x20for\x20example\x20product\x20copy,\x20rewrite\x20benefits',
    'skillInstructionsLabel': 'Instructions',
    'skillSave': 'Save',
    'skillEditorCancel': "Cancel",
    'skillValidationRequired': "When to use and Instructions are required.",
    'skillValidationName': 'Use\x20lowercase\x20letters,\x20numbers,\x20and\x20hyphens,\x20up\x20to\x2064\x20characters.',
    'skillSaveDone': "Saved Skill: {name}",
    'skillSaveFailed': 'Skill\x20save\x20failed.',
    'skillSaveDuplicate': "A Skill with this name already exists.",
    'skillSaveReadOnly': 'This\x20external\x20Skill\x20can\x20only\x20be\x20edited\x20in\x20its\x20folder.',
    'skillSaveRefreshFailed': 'The\x20Skill\x20was\x20saved,\x20but\x20the\x20list\x20could\x20not\x20refresh.\x20Refresh\x20it\x20again.'
  })
});