import { getLocale } from '../../i18n/index.js';
import { AGENT_SKILL_PANEL_TEXT } from './agentSkillPanelText.js';
export const AGENT_PANEL_LOCALES = Object["freeze"](["zh-CN", 'en-US']);
const PANEL_TEXT = Object["freeze"]({
  'zh-CN': Object["freeze"]({
    ...AGENT_SKILL_PANEL_TEXT["zh-CN"],
    'actionsPrepared': '已完成准备步骤。',
    'addReference': "添加画布内容 / 引用参考",
    'removeReference': "移除入参",
    'attachSelected': "已添加 {count} 个素材入参。",
    'attachSelectedEmpty': "先在画布选中素材节点，再添加为入参。",
    'materialPickStarted': "请选择画布上的素材节点作为 Agent 入参。",
    'materialPickCancelled': "已退出素材拾取。",
    'materialPickUnsupported': "请选择图片、视频、音频或文本素材节点。",
    'completed': "已完成",
    'confirmUserMessage': '确定',
    'confirmTitle': '请确认',
    'generate': '开始生成',
    'generateBatch': '批量开始生成',
    'graphConnect': "连接节点",
    'layoutAlign': '对齐节点',
    'layoutArrangeRow': "横向排列节点",
    'nodeCreate': "创建节点",
    'nodeCreateImage': "创建图片节点",
    'nodeCreateVideo': '创建视频节点',
    'nodeCreateAudio': "创建音频节点",
    'nodeCreateText': "创建文本节点",
    'nodeDelete': "删除节点",
    'nodeSetParams': "设置生成参数",
    'nodeSetPrompt': "写入提示词",
    'pending': "待确认",
    'model': "使用模型",
    'prompt': "Prompt 摘要",
    'editableParams': '可调整参数',
    'advancedSettings': "高级设置",
    'paramUpdateFailed': "参数更新失败。",
    'inputSource': '输入来源',
    'batchNodes': "生成节点",
    'traceSummary': '策略摘要',
    'diagnosticTitle': "失败诊断",
    'diagnosticStep': '第\x20{step}\x20步',
    'diagnosticCompleted': '已完成\x20{count}\x20步',
    'diagnosticDetails': "查看诊断详情",
    'diagnosticDetailsHide': "收起诊断详情",
    'diagnosticErrorCode': '错误代码：{code}',
    'recoveryTitle': "可以这样恢复",
    'recoveryEditPromptDraft': "请修改刚才失败的生成提示词：",
    'recoveryChangeModelDraft': "请为刚才失败的生成换一个模型：",
    'recoveryEditPromptNotice': "已进入重新规划：修改提示词后发送。",
    'recoveryChangeModelNotice': "已进入重新规划：写明想换的模型后发送。",
    'recoveryEditRequestNotice': '已恢复原需求，请修改后重新发送。',
    'runStepsTitle': "执行步骤",
    'historyTitle': "历史记录",
    'historyEmpty': "当前项目还没有历史对话",
    'historyOpen': "打开对话",
    'historyDelete': "删除对话",
    'unfinishedNotice': "上次任务未完成，请重新发起。",
    'uploadMaterial': "上传素材",
    'uploadMaterialFailed': '上传素材失败，请稍后重试。',
    'uploadMaterialMissing': '上传素材入口暂不可用。',
    'uploadMaterialReady': '已上传并添加为素材入参。',
    'readDocument': "读取文档",
    'documentAttached': "已添加 {count} 个文档，仅用于本轮对话。",
    'documentLimit': '每轮最多读取\x20{count}\x20个文档。',
    'copyMessage': '复制消息',
    'copySelection': "复制选中文本",
    'copyMessageDone': "已复制。",
    'copyMessageFailed': "复制失败，请手动复制。",
    'copyMessageImageLabel': '图片',
    'copyMessageNodeLabel': '节点',
    'copyMessageSeparator': '：',
    'imageResultOpen': "放大查看图片",
    'customShortcutEmpty': "先在输入框写好提示词，再保存为自定义快捷卡片。",
    'customShortcutPanelTitle': "自定义快捷用法",
    'customShortcutPanelDesc': "保存常用提示词，之后可直接点上方快捷卡片填入输入栏。",
    'customShortcutNameLabel': '名称',
    'customShortcutNamePlaceholder': "例如：产品图检查",
    'customShortcutPromptLabel': '提示词',
    'customShortcutPromptPlaceholder': "写下要复用的完整提示词",
    'customShortcutNew': '新建',
    'customShortcutSave': '保存',
    'customShortcutDelete': '删除',
    'customShortcutClose': '关闭',
    'customShortcutDeleted': "已删除自定义快捷卡片。",
    'customShortcutSaved': '已保存为自定义快捷卡片。',
    'waiting': "正在思考",
    'quickActionCanvasReviewLabel': "梳理画布",
    'quickActionCanvasReviewPrompt': "请阅读当前画布上的素材、节点和连线，梳理这个项目的创作目标、素材分组、当前进展，并给出下一步最该做的 3 件事。",
    'quickActionGapCheckLabel': "补齐链路",
    'quickActionGapCheckPrompt': "请检查当前画布从素材输入到生成结果的链路是否完整，指出缺少的节点、入参、模型选择或连线，并给出可直接执行的补齐方案。",
    'quickActionStoryboardLabel': "生成分镜",
    'quickActionStoryboardPrompt': "请基于当前画布素材，输出一版适合短视频或图像创作的分镜方案，包括每个镜头的画面、动作、提示词重点和需要引用的素材。",
    'quickActionSelectedTuneLabel': "优化选中",
    'quickActionSelectedTunePrompt': "请重点分析我当前选中的画布节点，结合相连节点和入参，给出提示词、参数、构图、时长、比例以及后续节点衔接的优化建议。",
    'legacyQuickActionExpandPromptLabel': "扩写提示词",
    'legacyQuickActionExpandPromptPrompt': "请结合当前画布素材和我的输入，扩写成更完整、可执行的创作提示词。",
    'legacyQuickActionStoryboardLabel': "生成分镜方案",
    'legacyQuickActionStoryboardPrompt': "请根据当前画布素材和我的需求，拆成清晰的分镜方案与下一步执行建议。",
    'legacyQuickActionGapCheckLabel': "检查画布缺口",
    'legacyQuickActionGapCheckPrompt': "请检查当前画布素材、节点和连线是否完整，指出缺口并给出补齐建议。",
    'placeholderUpload': "上传素材后会作为本次 Agent 入参。",
    'placeholderCustom': "打开自定义快捷用法面板。",
    'placeholderSkills': '打开本地\x20Skill\x20管理面板。',
    'placeholderFallback': "该入口会在后续接入。",
    'executionModeAuto': "自动执行",
    'executionModeManual': "手动确认",
    'modelSelection': '模型选择',
    'gapValue': "间距 {value}",
    'newConversationFallback': "新对话",
    'panelAria': "Canvas Agent 侧边栏",
    'resizeAria': "调整 Agent 侧边栏宽度",
    'betaBadge': "测试版",
    'newConversation': '新建对话',
    'close': '关闭',
    'greetingKicker': 'Hi，欢迎回来',
    'greetingTitle': "今天一起创作点什么？",
    'confirmExecute': "确认执行",
    'cancel': '取消',
    'addSelectedReference': "从选中素材添加入参",
    'inputPlaceholder': '描述创意或需求，输入\x20/\x20使用\x20Skill',
    'add': '添加',
    'agentMode': "Agent 模式",
    'send': '发送',
    'stop': '停止\x20Agent',
    'stopRequested': '已请求停止；晚到的模型结果不会执行。',
    'newConversationNotice': '已新建对话。',
    'executionModeSaved': '执行模式已保存；本轮不会改变确认策略。'
  }),
  'en-US': Object["freeze"]({
    ...AGENT_SKILL_PANEL_TEXT["en-US"],
    'actionsPrepared': 'Preparation\x20is\x20complete.',
    'addReference': "Add canvas context / references",
    'removeReference': "Remove reference",
    'attachSelected': "Added {count} material reference(s).",
    'attachSelectedEmpty': "Select canvas material nodes before adding references.",
    'materialPickStarted': "Pick a canvas material node to use as Agent input.",
    'materialPickCancelled': "Material picking cancelled.",
    'materialPickUnsupported': "Pick an image, video, audio, or text material node.",
    'completed': "Completed",
    'confirmUserMessage': "Confirm",
    'confirmTitle': "Confirm",
    'generate': 'Start\x20generation',
    'generateBatch': "Start batch generation",
    'graphConnect': "Connect nodes",
    'layoutAlign': "Align nodes",
    'layoutArrangeRow': "Arrange nodes horizontally",
    'nodeCreate': 'Create\x20node',
    'nodeCreateImage': "Create image node",
    'nodeCreateVideo': "Create video node",
    'nodeCreateAudio': "Create audio node",
    'nodeCreateText': "Create text node",
    'nodeDelete': "Delete node",
    'nodeSetParams': "Set generation parameters",
    'nodeSetPrompt': 'Set\x20prompt',
    'pending': "Pending confirmation",
    'model': "Model",
    'prompt': "Prompt summary",
    'editableParams': 'Editable\x20parameters',
    'advancedSettings': 'Advanced\x20settings',
    'paramUpdateFailed': 'Parameter\x20update\x20failed.',
    'inputSource': 'Input\x20source',
    'batchNodes': 'Generation\x20nodes',
    'traceSummary': "Policy summary",
    'diagnosticTitle': "Failure diagnostics",
    'diagnosticStep': "Step {step}",
    'diagnosticCompleted': '{count}\x20completed',
    'diagnosticDetails': 'View\x20diagnostic\x20details',
    'diagnosticDetailsHide': "Hide diagnostic details",
    'diagnosticErrorCode': "Error code: {code}",
    'recoveryTitle': "Recovery options",
    'recoveryEditPromptDraft': "Revise the failed generation prompt: ",
    'recoveryChangeModelDraft': "Switch the failed generation to another model: ",
    'recoveryEditPromptNotice': "Replanning draft is ready. Edit the prompt and send.",
    'recoveryChangeModelNotice': 'Replanning\x20draft\x20is\x20ready.\x20Name\x20the\x20model\x20you\x20want\x20and\x20send.',
    'recoveryEditRequestNotice': 'The\x20original\x20request\x20is\x20restored.\x20Edit\x20it\x20and\x20send\x20again.',
    'runStepsTitle': "Execution steps",
    'historyTitle': "History",
    'historyEmpty': 'No\x20conversation\x20history\x20in\x20this\x20project\x20yet.',
    'historyOpen': "Open conversation",
    'historyDelete': "Delete conversation",
    'unfinishedNotice': "The last run did not finish. Please start the request again.",
    'uploadMaterial': 'Upload\x20material',
    'uploadMaterialFailed': "Material upload failed. Please try again.",
    'uploadMaterialMissing': "Material upload is unavailable.",
    'uploadMaterialReady': 'Uploaded\x20and\x20added\x20as\x20a\x20material\x20reference.',
    'readDocument': 'Read\x20document',
    'documentAttached': "Added {count} document(s) for this turn only.",
    'documentLimit': 'You\x20can\x20read\x20up\x20to\x20{count}\x20documents\x20per\x20turn.',
    'copyMessage': 'Copy\x20message',
    'copySelection': 'Copy\x20selected\x20text',
    'copyMessageDone': 'Copied.',
    'copyMessageFailed': "Copy failed. Please copy manually.",
    'copyMessageImageLabel': "Image",
    'copyMessageNodeLabel': 'Node',
    'copyMessageSeparator': ':\x20',
    'imageResultOpen': 'Open\x20image\x20preview',
    'customShortcutEmpty': "Write a prompt first, then save it as a custom shortcut.",
    'customShortcutPanelTitle': 'Custom\x20shortcuts',
    'customShortcutPanelDesc': "Save reusable prompts and insert them from the quick cards above.",
    'customShortcutNameLabel': "Name",
    'customShortcutNamePlaceholder': "Example: product photo check",
    'customShortcutPromptLabel': "Prompt",
    'customShortcutPromptPlaceholder': "Write the reusable prompt",
    'customShortcutNew': 'New',
    'customShortcutSave': "Save",
    'customShortcutDelete': "Delete",
    'customShortcutClose': "Close",
    'customShortcutDeleted': "Custom shortcut deleted.",
    'customShortcutSaved': "Saved as a custom shortcut.",
    'waiting': "Thinking",
    'quickActionCanvasReviewLabel': "Review canvas",
    'quickActionCanvasReviewPrompt': "Read the materials, nodes, and connections on the current canvas. Summarize the project goal, material groups, current progress, and the 3 most useful next steps.",
    'quickActionGapCheckLabel': 'Complete\x20flow',
    'quickActionGapCheckPrompt': 'Check\x20whether\x20the\x20current\x20canvas\x20flow\x20is\x20complete\x20from\x20material\x20input\x20to\x20generated\x20result.\x20Point\x20out\x20missing\x20nodes,\x20inputs,\x20model\x20choices,\x20or\x20connections,\x20and\x20provide\x20an\x20executable\x20completion\x20plan.',
    'quickActionStoryboardLabel': "Create storyboard",
    'quickActionStoryboardPrompt': "Based on the current canvas materials, create a storyboard plan for short-video or image creation. Include each shot's image, action, prompt focus, and referenced materials.",
    'quickActionSelectedTuneLabel': "Tune selection",
    'quickActionSelectedTunePrompt': "Focus on my currently selected canvas node. Use connected nodes and inputs to suggest improvements to prompt, parameters, composition, duration, aspect ratio, and downstream node handoff.",
    'legacyQuickActionExpandPromptLabel': "Expand prompt",
    'legacyQuickActionExpandPromptPrompt': "Use the current canvas materials and my input to expand this into a complete, executable creation prompt.",
    'legacyQuickActionStoryboardLabel': "Storyboard plan",
    'legacyQuickActionStoryboardPrompt': "Use the current canvas materials and my request to break this into a clear storyboard plan and next-step recommendations.",
    'legacyQuickActionGapCheckLabel': "Check canvas gaps",
    'legacyQuickActionGapCheckPrompt': "Check whether the current canvas materials, nodes, and connections are complete. Point out gaps and recommend fixes.",
    'placeholderUpload': "Uploaded materials will be used as Agent inputs for this run.",
    'placeholderCustom': "Open the custom shortcut panel.",
    'placeholderSkills': "Open the local Skill manager.",
    'placeholderFallback': "This entry will be connected later.",
    'executionModeAuto': "Auto execute",
    'executionModeManual': "Manual confirm",
    'modelSelection': "Model selection",
    'gapValue': 'Gap\x20{value}',
    'newConversationFallback': "New conversation",
    'panelAria': "Canvas Agent sidebar",
    'resizeAria': "Resize Agent sidebar",
    'betaBadge': "Beta",
    'newConversation': 'New\x20conversation',
    'close': "Close",
    'greetingKicker': "Hi, welcome back",
    'greetingTitle': "What shall we create today?",
    'confirmExecute': 'Confirm\x20execution',
    'cancel': "Cancel",
    'addSelectedReference': "Add inputs from selected materials",
    'inputPlaceholder': "Describe an idea or request, type / to use a Skill",
    'add': "Add",
    'agentMode': "Agent mode",
    'send': 'Send',
    'stop': "Stop Agent",
    'stopRequested': "Stop requested. Late model results will not be executed.",
    'newConversationNotice': "New conversation created.",
    'executionModeSaved': "Execution mode saved. This turn will keep the current confirmation policy."
  })
});
function normalizePanelLocale(_0x46419b = getLocale()) {
  return String(_0x46419b || '')["toLowerCase"]()["startsWith"]('en') ? "en-US" : "zh-CN";
}
export function agentPanelText(_0x3287f8, _0x5bc9c = getLocale()) {
  const _0x17c53b = normalizePanelLocale(_0x5bc9c);
  return PANEL_TEXT[_0x17c53b]?.[_0x3287f8] || PANEL_TEXT['zh-CN'][_0x3287f8] || _0x3287f8;
}
export function formatAgentPanelText(_0x2972be, _0x4c409c = {}, _0xfe1aa1 = getLocale()) {
  return agentPanelText(_0x2972be, _0xfe1aa1)["replace"](/\{(\w+)\}/g, (_0xa1296d, _0x17adc1) => _0x4c409c[_0x17adc1] == null ? '' : String(_0x4c409c[_0x17adc1]));
}