import { SAVED_WORKFLOW_LIBRARY_ENTRY_ENABLED } from '../config/productFeatures.js';
const createShortcut = (_0x458877, _0x3f387e, {
  hidden = ![],
  disabled = ![]
} = {}) => Object["freeze"]({
  'label': _0x458877,
  'keys': Object["freeze"]([]),
  'group': _0x3f387e,
  'contextMenuOnly': !![],
  ...(hidden ? {
    'hidden': !![]
  } : {}),
  ...(disabled ? {
    'disabled': !![]
  } : {})
});
const CANVAS_GROUP = '右键菜单·画布';
const MATERIAL_GROUP = '右键菜单·素材与文件';
const PROJECT_GROUP = "右键菜单·项目与工作区";
const FEATURE_GROUP = '右键菜单·功能面板';
const WEB_GROUP = "右键菜单·网页预览";
const createWorkflowShortcut = _0x2cc7ce => createShortcut(_0x2cc7ce, FEATURE_GROUP, {
  'hidden': !SAVED_WORKFLOW_LIBRARY_ENTRY_ENABLED,
  'disabled': !SAVED_WORKFLOW_LIBRARY_ENTRY_ENABLED
});
export const CONTEXT_MENU_SHORTCUTS = Object['freeze']({
  'context-canvas-open-add-node-menu': createShortcut('画布：添加节点', CANVAS_GROUP),
  'context-canvas-open-node-section-generation': createShortcut('画布：打开生成节点分类', CANVAS_GROUP),
  'context-canvas-open-node-section-source': createShortcut("画布：打开源节点分类", CANVAS_GROUP),
  'context-canvas-open-node-section-function': createShortcut("画布：打开功能节点分类", CANVAS_GROUP),
  'context-canvas-material-comparison': createShortcut('画布：素材对比', CANVAS_GROUP),
  'context-canvas-create-collage': createShortcut("画布：创建拼图", CANVAS_GROUP),
  'context-canvas-add-to-library': createShortcut("画布：添加到素材库", CANVAS_GROUP),
  'context-canvas-reveal-file': createShortcut("画布：打开素材所在文件夹", CANVAS_GROUP),
  'context-canvas-open-output-folder': createShortcut("画布：打开输出目录", CANVAS_GROUP),
  'context-canvas-duplicate': createShortcut("画布：复制节点（含连线）", CANVAS_GROUP),
  'context-canvas-copy-text': createShortcut("画布：复制文本内容", CANVAS_GROUP),
  'context-canvas-create-connected-ai-text': createShortcut("画布：连接生成文本节点", CANVAS_GROUP),
  'context-canvas-create-connected-ai-image': createShortcut('画布：连接生成图像节点', CANVAS_GROUP),
  'context-canvas-create-connected-ai-video': createShortcut('画布：连接生成视频节点', CANVAS_GROUP),
  'context-canvas-create-connected-ai-audio': createShortcut("画布：连接生成音频节点", CANVAS_GROUP),
  'context-canvas-open-grid-menu': createShortcut('画布：创建宫格图', CANVAS_GROUP),
  'context-canvas-create-grid-4': createShortcut('画布：创建\x204\x20宫格', CANVAS_GROUP),
  'context-canvas-create-grid-9': createShortcut("画布：创建 9 宫格", CANVAS_GROUP),
  'context-canvas-create-grid-16': createShortcut("画布：创建 16 宫格", CANVAS_GROUP),
  'context-canvas-create-grid-25': createShortcut("画布：创建 25 宫格", CANVAS_GROUP),
  'context-canvas-create-source-image': createShortcut('画布：创建源图像节点', CANVAS_GROUP),
  'context-canvas-create-source-video': createShortcut("画布：创建源视频节点", CANVAS_GROUP),
  'context-canvas-create-source-audio': createShortcut("画布：创建源音频节点", CANVAS_GROUP),
  'context-canvas-create-panorama-scene': createShortcut("画布：创建 3D 导演台", CANVAS_GROUP),
  'context-canvas-create-panorama-360': createShortcut("画布：创建 360 全景图", CANVAS_GROUP),
  'context-canvas-create-storyboard': createShortcut("画布：创建宫格图节点", CANVAS_GROUP),
  'context-canvas-create-storyboard-script': createShortcut("画布：创建分镜脚本节点", CANVAS_GROUP),
  'context-canvas-create-collage-node': createShortcut("画布：创建拼图节点", CANVAS_GROUP),
  'context-canvas-create-whiteboard': createShortcut("画布：创建白板节点", CANVAS_GROUP),
  'context-canvas-create-media-clip': createShortcut("画布：创建剪辑节点", CANVAS_GROUP),
  'context-canvas-create-debug': createShortcut("画布：创建调试节点", CANVAS_GROUP),
  'context-align-grid-auto': createShortcut("对齐：自动宫格排列", CANVAS_GROUP),
  'context-align-grid-2': createShortcut("对齐：每行 2 个", CANVAS_GROUP),
  'context-align-grid-3': createShortcut("对齐：每行 3 个", CANVAS_GROUP),
  'context-align-grid-4': createShortcut("对齐：每行 4 个", CANVAS_GROUP),
  'context-align-grid-5': createShortcut('对齐：每行\x205\x20个', CANVAS_GROUP),
  'context-history-add-to-canvas': createShortcut("文件管理：添加到画布", MATERIAL_GROUP),
  'context-history-fullscreen': createShortcut("文件管理：全屏预览", MATERIAL_GROUP),
  'context-history-reveal': createShortcut("文件管理：在文件夹中显示", MATERIAL_GROUP),
  'context-history-delete': createShortcut('文件管理：删除', MATERIAL_GROUP),
  'context-material-load-item': createShortcut("素材库：添加素材项到画布", MATERIAL_GROUP),
  'context-material-rename-item': createShortcut("素材库：重命名素材项", MATERIAL_GROUP),
  'context-material-folder-toggle': createShortcut("素材库：展开或收起文件夹", MATERIAL_GROUP),
  'context-material-folder-rename': createShortcut('素材库：重命名文件夹', MATERIAL_GROUP),
  'context-material-folder-delete': createShortcut('素材库：删除文件夹', MATERIAL_GROUP),
  'context-material-favorite': createShortcut("素材库：收藏素材", MATERIAL_GROUP),
  'context-material-unfavorite': createShortcut("素材库：取消收藏素材", MATERIAL_GROUP),
  'context-material-rename': createShortcut("素材库：重命名素材", MATERIAL_GROUP),
  'context-material-open-move-menu': createShortcut("素材库：移动到分类", MATERIAL_GROUP),
  'context-material-duplicate': createShortcut("素材库：创建副本", MATERIAL_GROUP),
  'context-material-download': createShortcut("素材库：下载素材", MATERIAL_GROUP),
  'context-material-delete': createShortcut("素材库：删除素材", MATERIAL_GROUP),
  'context-material-cancel-delete': createShortcut('素材库：取消删除素材', MATERIAL_GROUP),
  'context-material-confirm-delete': createShortcut("素材库：确认删除素材", MATERIAL_GROUP),
  'context-media-clip-export-to-canvas': createShortcut("剪辑素材：导出到画布", MATERIAL_GROUP),
  'context-media-clip-enable-audio': createShortcut('剪辑素材：启用音频', MATERIAL_GROUP),
  'context-media-clip-disable-audio': createShortcut('剪辑素材：禁用音频', MATERIAL_GROUP),
  'context-media-clip-delete': createShortcut("剪辑素材：删除", MATERIAL_GROUP),
  'context-project-rename': createShortcut("画布项目：重命名", PROJECT_GROUP),
  'context-project-delete': createShortcut("画布项目：删除", PROJECT_GROUP),
  'context-canvas-tab-save-as': createShortcut('画布标签：另存为', PROJECT_GROUP),
  'context-canvas-tab-collect-project': createShortcut("画布标签：整理项目文件", PROJECT_GROUP),
  'context-canvas-tab-delete': createShortcut("画布标签：删除", PROJECT_GROUP),
  'context-workspace-open-project': createShortcut("工作区项目：打开", PROJECT_GROUP),
  'context-workspace-rename-project': createShortcut("工作区项目：重命名", PROJECT_GROUP),
  'context-workspace-duplicate-project': createShortcut("工作区项目：创建副本", PROJECT_GROUP),
  'context-workspace-collect-project': createShortcut("工作区项目：收集", PROJECT_GROUP),
  'context-workspace-archive-project': createShortcut("工作区项目：归档", PROJECT_GROUP),
  'context-workspace-unarchive-project': createShortcut("工作区项目：取消归档", PROJECT_GROUP),
  'context-workspace-delete-project': createShortcut("工作区项目：删除", PROJECT_GROUP),
  'context-story-switch-version': createShortcut("故事工作区：切换版本", PROJECT_GROUP),
  'context-story-delete-version': createShortcut("故事工作区：删除版本", PROJECT_GROUP),
  'context-story-select-clip': createShortcut("故事工作区：选择片段", PROJECT_GROUP),
  'context-story-delete-clip': createShortcut("故事工作区：删除片段", PROJECT_GROUP),
  'context-story-view-asset': createShortcut("故事工作区：查看素材", PROJECT_GROUP),
  'context-story-delete-asset': createShortcut('故事工作区：删除素材', PROJECT_GROUP),
  'context-person-switch-result': createShortcut("换人工作区：切换结果", PROJECT_GROUP),
  'context-person-delete-result': createShortcut("换人工作区：删除结果", PROJECT_GROUP),
  'context-audio-voice-toggle-imitate-tone': createShortcut('配音片段：模仿音色', FEATURE_GROUP),
  'context-audio-voice-open-model-menu': createShortcut("配音片段：选择模型", FEATURE_GROUP),
  'context-audio-voice-use-global-model': createShortcut('配音片段：使用全局模型', FEATURE_GROUP),
  'context-audio-voice-use-generated': createShortcut('配音片段：使用生成音频', FEATURE_GROUP),
  'context-audio-voice-use-source': createShortcut('配音片段：使用原始音频', FEATURE_GROUP),
  'context-audio-voice-download-source': createShortcut("配音片段：下载原始音频", FEATURE_GROUP),
  'context-audio-voice-download-generated': createShortcut("配音片段：下载生成音频", FEATURE_GROUP),
  'context-audio-voice-add-source-to-canvas': createShortcut("配音片段：原音频加入画布", FEATURE_GROUP),
  'context-audio-voice-add-generated-to-canvas': createShortcut("配音片段：转换音频加入画布", FEATURE_GROUP),
  'context-audio-voice-delete': createShortcut('配音片段：删除', FEATURE_GROUP),
  'context-runninghub-load-app': createShortcut("自定义 AI 应用：加载", FEATURE_GROUP),
  'context-runninghub-delete-app': createShortcut("自定义 AI 应用：删除", FEATURE_GROUP),
  'context-runninghub-rename-param': createShortcut("自定义 AI 应用：重命名参数", FEATURE_GROUP),
  'context-runninghub-edit-description': createShortcut('自定义\x20AI\x20应用：编辑说明', FEATURE_GROUP),
  'context-runninghub-choose-control': createShortcut("自定义 AI 应用：选择控件类型", FEATURE_GROUP),
  'context-runninghub-remove-param': createShortcut('自定义\x20AI\x20应用：移除参数', FEATURE_GROUP),
  'context-runninghub-remove-input': createShortcut("自定义 AI 应用：移除输入", FEATURE_GROUP),
  'context-task-cancel': createShortcut('任务中心：取消任务', FEATURE_GROUP),
  'context-task-reveal': createShortcut('任务中心：在文件夹中显示', FEATURE_GROUP),
  'context-task-copy-error': createShortcut("任务中心：复制错误", FEATURE_GROUP),
  'context-workflow-details': createWorkflowShortcut("工作流：查看详情"),
  'context-workflow-load': createWorkflowShortcut("工作流：加载到画布"),
  'context-workflow-rename': createWorkflowShortcut("工作流：重命名"),
  'context-workflow-edit-meta': createWorkflowShortcut("工作流：编辑信息"),
  'context-workflow-update-content': createWorkflowShortcut("工作流：更新内容"),
  'context-workflow-delete': createWorkflowShortcut("工作流：删除"),
  'context-node-manager-rename': createShortcut("节点管理：重命名", FEATURE_GROUP),
  'context-node-manager-download': createShortcut("节点管理：下载", FEATURE_GROUP),
  'context-node-manager-delete': createShortcut("节点管理：删除", FEATURE_GROUP),
  'context-agent-open-image': createShortcut("Agent：打开图像", FEATURE_GROUP),
  'context-agent-open-history': createShortcut("Agent：打开历史会话", FEATURE_GROUP),
  'context-agent-delete-history': createShortcut("Agent：删除历史会话", FEATURE_GROUP),
  'context-web-image-add-to-canvas': createShortcut("网页预览：图像加入画布", WEB_GROUP),
  'context-web-image-reverse-create': createShortcut('网页预览：反推提示词并创建', WEB_GROUP),
  'context-web-image-reverse-generate': createShortcut("网页预览：反推提示词并生成", WEB_GROUP),
  'context-web-copy-text': createShortcut("网页预览：复制文本", WEB_GROUP),
  'context-web-open-text-node-menu': createShortcut("网页预览：打开文本节点菜单", WEB_GROUP),
  'context-web-text-to-source': createShortcut("网页预览：文本发送到源节点", WEB_GROUP),
  'context-web-text-to-generated': createShortcut("网页预览：文本发送到生成文本", WEB_GROUP),
  'context-web-open-image-node-menu': createShortcut("网页预览：打开图像节点菜单", WEB_GROUP),
  'context-web-text-to-image-create': createShortcut("网页预览：文本创建图像节点", WEB_GROUP),
  'context-web-text-to-image-generate': createShortcut("网页预览：文本生成图像", WEB_GROUP),
  'context-web-open-video-node-menu': createShortcut("网页预览：打开视频节点菜单", WEB_GROUP),
  'context-web-text-to-video-create': createShortcut('网页预览：文本创建视频节点', WEB_GROUP),
  'context-web-text-to-video-generate': createShortcut("网页预览：文本生成视频", WEB_GROUP)
});
export const CONTEXT_MENU_SHORTCUT_IDS = Object['freeze'](Object["keys"](CONTEXT_MENU_SHORTCUTS));
export function isContextMenuShortcut(_0x51c11c) {
  return Object["prototype"]["hasOwnProperty"]["call"](CONTEXT_MENU_SHORTCUTS, String(_0x51c11c || ''));
}